### ISSUE TITLE
the minimum version for windows should be 1.14

### ISSUE THREAD

**Issue by fgregg** [scipy/oldest-supported-numpy#37]
before numpy 1.14, on windows, if an extension included npymath, there would be [compiler incompatibility with the windows numpy wheel](https://github.com/numpy/numpy/issues/9958).

This was fixed in 1.14. For `win32`, that should be the minimum version.

**Comment by rgommers** [comment]
Thanks @fgregg. That sounds right at first sight. Could you please add some details of the problem you're seeing, that will be very useful to judge the severity and decide whether we can actually do this or not.

The downside is, I think, that it may break users who successfully use MSVC 2017 with their package and have numpy `== 1.13.x` somewhere.

**Comment by fgregg** [comment]
sure! here’s a build failing with numpy==1.13.3

https://github.com/dedupeio/pyhacrf/runs/4574721371?check_suite_focus=true

this is the heart of the problem:

```
    fatal error C1047: The object or library file 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\pip-build-env-asy33t2u\\overlay\\Lib\\site-packages\\numpy\\core\\lib\npymath.lib' was created by a different version of the compiler than other objects like 'build\temp.win32-3.6\Release\pyhacrf\algorithms.obj'; rebuild all objects and libraries with the same compiler
    LINK : fatal error LNK1257: code generation failed
```

here’s the same package building with numpy==1.14.0

https://github.com/dedupeio/pyhacrf/runs/4574816277?check_suite_focus=true

**Comment by rgommers** [comment]
I've looked at this again, and I'm leaning towards keeping things as they are, and telling devs who run into this problem that they should not use `oldest-supported-numpy` but copy the requirements to their `pyproject.toml`.

Rationale:
- This bug is only relevant for developers of packages that: still support Python 3.5-3.6 (a small fraction of packages today), build against `npymath` (a small fraction of NumPy C API users) and use MSVC 2015 (stats on this unclear).
- If we bump the requirement now, there is a chance of breaking packages that worked before. E.g. something like scikit-learn has a numpy 1.13.3 minimum version requirement, and that would then just no longer work. Environments containing such packages _and_ pinning numpy 1.13.x at runtime would build from an sdist but break at runtime.
- In general we should be quite reluctant to change version pins for releases which do have (working) NumPy wheels.

@astrofrog, @mattip, @seberg, @charris this kind of issue isn't trivial to decide on, if you have other thoughts/considerations then I'd love to hear them.

**Comment by rgommers** [comment]
We're staying with the status quo, so I'll close this. Thanks for looking into this @fgregg
