### ISSUE TITLE
No 1.21.4 wheel available for cp310-win32

### ISSUE THREAD

**Issue by fgregg** [scipy/oldest-supported-numpy#45]
numpy 1.22.3 is the first release on pypi to have binary wheels for cpython 3.10 on win32, but setup.cfg says to use 1.21.4

https://github.com/scipy/oldest-supported-numpy/blob/8f36bbf7648f6360084212e425816e2c78433973/setup.cfg#L56

**Comment by matham** [comment]
Did the latest release fix the issue for you? Because it didn't for me (for the dependency I was having an issue with on the CI), and I'm thinking that maybe checking whether `platform_machine` is x86 is incorrect. Because I don't think it's checking whether python is 32 bit, just whether the OS is 32 bit. Otherwise it doesn't make sense why the latest release is still giving me the issue (and I don't have a 32 bit python to check with handy).

You can see here what is available: https://peps.python.org/pep-0508/#environment-markers

**Comment by matham** [comment]
I've added https://github.com/scipy/oldest-supported-numpy/pull/47 to clearly show the issue. It seems we cannot differentiate python bitness :( so my type of solution won't work. I can make a PR just bumping the min numpy for Windows if @rgommers approves (and remove the changes from the last PR).

**Comment by rgommers** [comment]
Argh yes, that rings a bell. We indeed need Python bitness, not `x86` platform.

> i think maybe we need `sys_platform=win32`, but i'm not sure.

No, that's not it either - `win32` means "Windows" (also 64-bit, despite the 32 in the name).

> I can make a PR just bumping the min numpy for Windows if @rgommers approves (and remove the changes from the last PR).

I think (but haven't verified) that we cannot do this. Updating to 1.22.3 would mean that for `x86_64` a wheel built against that would work back to `1.22.0`, but IIRC there's a runtime check that will prevent it to work with `1.21.x`. Maybe you have time to verify that @matham?

**Comment by matham** [comment]
>I think (but haven't verified) that we cannot do this. Updating to 1.22.3 would mean that for x86_64 a wheel built against that would work back to 1.22.0, but IIRC there's a runtime check that will prevent it to work with 1.21.x. Maybe you have time to verify that @matham?

I don't quite understand. Do you mean if I use numpy in e.g. a cython project linking to numpy, it's not runnable with numpy with older minor versions? I don't actually have a project using numpy in this way so I can't really test. I'm just adding these PRs to fix issues with some dependencies (pytables) I was adding mac apple silicon support to.

But, even if that's the case, is the issue that 1.22.0 is just too new? Because we already don't support e.g. 1.20.x that is only a year old.

**Comment by henryiii** [comment]
> Do you mean if I use numpy in e.g. a cython project linking to numpy, it's not runnable with numpy with older minor versions? 

That's the point of `oldest-supported-numpy`; you must compile against the oldest supported numpy (minor version) when using something like Cython (not pybind11, FYI). You can't compile against 1.22 and run with 1.21, but you can compile against 1.21 and run with 1.22.

IMO, the system bitness is not interesting when selecting wheels, while the Python bitness is. Is `platform_release` or `platform_version` at all helpful on Windows, say with an `in` statement? I'm also asking around.

**Comment by matham** [comment]
>Is platform_release or platform_version at all helpful on Windows, say with an in statement? I'm also asking around

I compared the (Python equivalent) value of every marker in the [table](https://peps.python.org/pep-0508/#environment-markers) for python 3.7 32 bit and 64 bit and they were identical. So I'm not sure there's a way to detect this.

**Comment by rgommers** [comment]
C API version did indeed increase from 1.21 to 1.22: https://github.com/numpy/numpy/blob/main/numpy/core/setup_common.py#L46-L47.

Building SciPy against 1.22 and then running its tests against 1.21 gives this error:
```
RuntimeError: module compiled against API version 0xf but this version of numpy is 0xe
```

So it looks like we cannot add a `1.22.3` requirement for 32-bit Python on Windows.

The `x86` change in gh-44 is probably not wrong (since you cannot run 64-bit Python on 32-bit Windows I think), but I'm inclined to revert it because it doesn't cover the most relevant case (32-bit Python on 64-bit Windows).

The immediate solution is to not use `oldest-supported-numpy` in your package for Python 3.10 on Windows (manually depend on the NumPy version you want instead).

**Comment by matham** [comment]
>The immediate solution is to not use oldest-supported-numpy in your package for Python 3.10 on Windows (manually depend on the NumPy version you want instead).

But at that point, what is the downside of pinning oldest-supported-numpy to 1.22.3 for 3.10 Windows and not supporting 1.21? That's anyway what you'd need to do if you want to support 32 bit on windows 3.10? Is that that for 64 bits we do want to support 1.21, even if 32 bit is not supported?

**Comment by rgommers** [comment]
> That's anyway what you'd need to do if you want to support 32 bit on windows 3.10? Is that that for 64 bits we do want to support 1.21, even if 32 bit is not supported?

Yes. 32-bit Python is very much niche by now (there weren't many complaints about NumPy not supporting it in 1.21.4 - 1.22.2), and I don't think we should drop 1.21 support for 64-bit Python. In addition, doing so now would be a backwards incompatible change, which is never a good thing to do.

**Comment by matham** [comment]
Ok, I reverted the change in #47 (but I left the test you added as it's still going to be useful).

**Comment by rgommers** [comment]
There's no change to be made here in `oldest-supported-numpy`. The two "correct" fixes would be:
1. Get packaging tooling to have an environment marker for Python bitness that can be used, or
2. Build and upload a 32-bit wheel for NumPy 1.21.4

In the absence of that, for people who need 32-bit Python support on Windows, the workaround is to add something like this to  their `pyproject.toml` file:
```
"numpy==1.22.3; python_version=='3.10' and platform_system=='Windows'",
"oldest-supported-numpy; python_version!='3.10' or platform_system!='Windows'",
```

Let's leave this issue open for a while in case others come looking for this info.

**Comment by charris** [comment]
Could do a 1.21.6 release if needed, In addition to a 32 bit 2.10 wheel I would also remove the C++ bits backported by mistake in 1.21.5. Could probably do a 1.21.4 wheel upload instead, but in that case would probably need to do one for 1.21.5 as well.

**Comment by rgommers** [comment]
If it's not too much trouble, that sounds like a decent solution @charris

**Comment by charris** [comment]
Which solution do you want, maybe all of them?

**Comment by rgommers** [comment]
> Could do a 1.21.6 release if needed, In addition to a 32 bit 2.10 wheel I would also remove the C++ bits backported by mistake in 1.21.5.

This one is best. Building against 1.21.6 and running against 1.21.4 is fine, so no new 1.21.4 wheel needed in that case.

**Comment by charris** [comment]
OK, will do.

**Comment by charris** [comment]
Turns out that 32 bit Python 3.10 is only available in vs2019, which is why it didn't show up before, so vs2019 is what I built it with. I don't think that should cause a problem, there have been no related complaints for NumPy 1.22.x.  vs2017 was supposed to be removed April 1, but it was still available for the other Windows builds. I was tempted to just move everything to vs2019 but thought that was a gamble.

Hmm, ISTR compatibility problems with 14.2 library that comes with vs2019, need to look into that.

**Comment by rgommers** [comment]
> Hmm, ISTR compatibility problems with 14.2 library that comes with vs2019, need to look into that.

It's separate versioning/toolchain, we can use 14.1 together with vs2019. And I believe that is what we do now on the numpy-wheels repo: https://github.com/MacPython/numpy-wheels/pull/146.

That is a bit of an involved backport though ....

**Comment by charris** [comment]
> That is a bit of an involved backport though.

Wasn't so bad. It is amazing how fast things bitrot these days :)

**Comment by rgommers** [comment]
Seeing the new release, thanks Chuck!

**Comment by charris** [comment]
> Seeing the new release,

I'm hoping there aren't any problems needing a 1.21.7. I ended up using vs2019 for all the Windows wheels...

**Comment by robbmcleod** [comment]
Hi, ran into this problem with NumExpr. Is the suggested fix still to use @rgommers suggestion of modifying the `pyproject.toml`?

**Comment by rgommers** [comment]
> Is `'/d2FH4-'` included? That's the only possible issue I know of. https://cibuildwheel.readthedocs.io/en/stable/faq/#windows-importerror-dll-load-failed-the-specific-module-could-not-be-found

Thanks for pointing that out. I think that is potentially an issue. The flag is not included in the build, and I don't think we're vendoring the new DLL (we are vendoring the regular `140` one). @charris was this on your radar already?

**Comment by rgommers** [comment]
The DLL issue is unrelated to the fix for this issue I believe, so I'll go ahead with merging gh-49 and a new release.

**Comment by charris** [comment]
> was this on your radar already?

No, and I'm not quite sure what it means :) We are starting to worry about the runtime library in the cibuildwheel builds we will use for 1.23.x, and I'm watching that.

**Comment by charris** [comment]
> @charris we should be vendoring msvcp140.dll

I thought all we needed was the msvcp141.dll? I'm not convinced our current nightly wheels have the correct library, we need to check that before we can release 1.23.x.

In any case, I would like to have clear guidelines as to what we _do_ need,

**Comment by charris** [comment]
The only dll in the current wheels is OpenBLAS.

**Comment by henryiii** [comment]
All versions of Python currently supported should already have `msvcp140.dll`. It's just `msvcp140_1.dll` that could be missing, since older Python's don't have it. It's easy to avoid needing it with the flag above. I expect there's a Python version (or patch versions) where Python is built with 2019+ and will always have the second DLL. MS includes `msvcp140_1.dll` with any new redistributable downloads now too.

I checked 3.10.4 and it does have both DLL's. Also 3.8.10 does too. 3.8.0 does not have the `_1` DLL.

**Comment by henryiii** [comment]
For versions that matter to numpy (didn't check 3.7), 3.8.0-3.8.2 are the only ones missing `msvcp140_1.dll`.

**Comment by charris** [comment]
@henryiii Thanks for the info, that helps understand what is going on. Is `msvp140_1.dll` the same as `msvp141.dll` (14.1)?

**Comment by henryiii** [comment]
I don't know what `msvp141.dll` is. The point of the 14.x series is they are all cross compatible, that is, something built on one can use the other - that's why there is only 140 when it comes to DLL's. But then they needed more in 2019, so they added `140_1`, which is an optional extra component, but not a truly "new" version, just additions. I'm not aware of anything past that yet. Though I'm not very familiar with MSVC2022 yet.

**Comment by charris** [comment]
@henryiii I'm going by the toolchains found on azure. There is 14.1, for vs2017, 14.2 for vs2019, and I assume 14.3 for vs2022. The whole nomenclature thing has me confused. As I understand it, compiling with earlier versioned toolchains will allow the binary to be linked with all later version libraries. So I suspect my confusion here is between toolchains and the DLL libraries.

**Comment by henryiii** [comment]
Regardless of which toolchain you use, there's only "one" redistributable they all use, v140, which started with MSVC2015. Before that, each one had it's own redistributable - you had to have downloaded one for each MSVC version. "One" is in quotes above because it's now two file - the original 2015 `msvcp140.dll` and a 2019 addition `msvcp140_1.dll`. If you download the redistributable pack today, it will list 2015-2022 as supported and will provide both DLLs.

I'm guessing the next "break" will happen if they produce a v15x series., and that's the point we'd need a new redistributable.

**Comment by henryiii** [comment]
I think Python is part of the reason they changed to this system, actually. MS hated having to provide the 2008 redistributable and compilers for Python 2.7 (v9x, IIRC), and they kept it available as a download for _years_ past when they normally do - they only removed the download a few months ago. I expect other libraries and packages cared too, but I know Python got special treatment due to the insane lifespan of 2.7. Now it's much easier to upgrade MSVC, and GHA/Azure is happy to drop old versions.

**Comment by charris** [comment]
@henryiii Maybe @isuruf can clarify the role of the toolchain version here. All I know at the moment is that we need to use the 14.1 toolchain for backward compatibility with, e.g., SciPy, and the default toolchain for vs2019 is 14.2. From what you say, they all use the DLL distributed with Python, and I assume Python sets some flags, so I am unclear on why the toolchain matters. Are there other libraries we need to worry about?

**Comment by charris** [comment]
The toolchain issue is to allow downstream to link to NumPy provided libraries, of which I think we provide two that are relevant: npymath and npyrandom, both of which are `*.lib` files. So those are the core of the problem.
