### ISSUE TITLE
The test suite isn't properly installing aarch64 wheels

### ISSUE THREAD

**Issue by BvB93** [scipy/oldest-supported-numpy#51]
As can be seen from, for example, an [(ubuntu-latest, 3.10, x64, yes)]( https://github.com/scipy/oldest-supported-numpy/runs/6062746968?check_suite_focus=true) test x86_64 wheels are installed despite the use of QEMU (see below). 
Could this be because the python executable itself is incompatible with aarch64?

```
Run pip install . --only-binary numpy
Processing /home/runner/work/oldest-supported-numpy/oldest-supported-numpy
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting numpy==1.21.6
  Downloading numpy-1.21.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 76.2 MB/s eta 0:00:00
Using legacy 'setup.py install' for oldest-supported-numpy, since package 'wheel' is not installed.
Installing collected packages: numpy, oldest-supported-numpy
  Running setup.py install for oldest-supported-numpy: started
  Running setup.py install for oldest-supported-numpy: finished with status 'done'
Successfully installed numpy-1.21.6 oldest-supported-numpy-2022.4.18
```

**Comment by rgommers** [comment]
Thanks @BvB93. This was recently added in gh-47. @matham would you be able to have a look at this?

**Comment by matham** [comment]
I guess simply installing qemu is not enough to make python available for testing. You'd still need to run tests in a docker container like: https://github.com/jamesturk/jellyfish/blob/fac51dc8fc0d196586e28d7f2ed37dafd56fbab4/.github/workflows/pythonpackage.yml#L80=. It only works for building because cibuildwheel has special feature to use QEMU.

I could either remove the test for aarch64, or work on adding the docker stuff like in the linked example.

**Comment by rgommers** [comment]
I'd say let's remove it. That's a lot of effort/complexity for something that isn't all that likely to catch issues - the regular native test runs should be enough.
