### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement oldest-supported-numpy (from versions: none)

### ISSUE THREAD

**Issue by yekaizhou** [scipy/oldest-supported-numpy#54]
i am using Python 2.7.12 and pip 20.3.4

**Comment by ilayn** [comment]
Python 2 support is dropped a few years ago hence it will not find any compatible version.

**Comment by yekaizhou** [comment]
is it possible to build it from source by python 2.7 to satisfy the requirement of other dependent packages?

**Comment by ilayn** [comment]
It has been quite a time window that most components are now geared towards Python 3.8 and onwards. Theoretically it might work however many libraries are not going to play nice with Python 2 restrictions since we have removed Python 2 specific parts after stopping the support for it. 

In general, I'd recommend spending time and energy on updating the system to a modern version instead of fighthing with Python 2. But emphasis on "recommend". You are certainly entitled to try otherwise. I will close the issue since it is not an issue but feel free to continue the discussion.

**Comment by yekaizhou** [comment]
thanks for your recommendation. but I have to continue on python 2.7 for consistency within our server.

could you tell me which version of oldest-supported-numpy is consistent with python 2.7?

many thanks

**Comment by rgommers** [comment]
The very first `oldest-supported-numpy` release (https://pypi.org/project/oldest-supported-numpy/0.1/) already required Python >= 3.5; there is no version that support Python 2.7

Instead of using `oldest-supported-numpy`, you should just use `numpy` or `numpy==<version-you-need>` in `install_requires` or `pyproject.toml`
